name: Windows-RDP

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
      - name: Enable RDP
        run: |
          net user "GOD OF GAMERZ" "GOD OF GAMERZ" /add
          net localgroup administrators "GOD OF GAMERZ" /add
          reg add "HKLM\System\CurrentControlSet\Control\Terminal Server" /v fDenyTSConnections /t REG_DWORD /d 0 /f
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      - name: Show RDP Info
        run: |
          echo "USERNAME: GOD OF GAMERZ"
          echo "PASSWORD: GOD OF GAMERZ"
          ipconfig

      - name: Keep VM Alive
        run: |
          Write-Host "VM running for 6 hours"
          Start-Sleep -Seconds 21600
