name: Windows-CRD

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
      - name: Install Chrome Remote Desktop
        run: |
          Invoke-WebRequest https://dl.google.com/edgedl/chrome-remote-desktop/chromeremotedesktophost.msi -OutFile crd.msi
          Start-Process msiexec.exe -ArgumentList "/i crd.msi /quiet /norestart" -Wait

      - name: Start Chrome Remote Desktop
        run: |
          echo "Go to https://remotedesktop.google.com/headless"
          echo "Copy the Windows command and paste it in the next step."

      - name: Keep VM Running
        run: |
          Write-Host "VM running for 6 hours"
          Start-Sleep -Seconds 21600
