name: Windows-HTTPS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:

      - name: Prepare Windows
        shell: pwsh
        run: |
          Write-Host "Preparing Windows VM"

      - name: Install Chrome Remote Desktop
        shell: pwsh
        run: |
          Invoke-WebRequest https://dl.google.com/edgedl/chrome-remote-desktop/chromeremotedesktophost.msi -OutFile crd.msi
          Start-Process msiexec.exe -ArgumentList "/i crd.msi /quiet /norestart" -Wait

      - name: Download Cloudflare Tunnel
        shell: pwsh
        run: |
          Invoke-WebRequest https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-windows-amd64.exe -OutFile cloudflared.exe

      - name: Start HTTPS Tunnel
        shell: pwsh
        run: |
          Write-Host "Starting Cloudflare Tunnel..."
          .\cloudflared.exe tunnel --url http://localhost:3389

      - name: Keep VM Alive
        shell: pwsh
        run: |
          Write-Host "VM running for about 6 hours"
          $end = (Get-Date).AddHours(6)
          while((Get-Date) -lt $end){
              Start-Sleep -Seconds 60
          }
