name: Windows-RDP-Playit

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 120

    steps:

      - name: Enable RDP
        shell: pwsh
        run: |
          net user gamer P@ssw0rd123! /add
          net localgroup administrators gamer /add
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      - name: Download Playit
        shell: pwsh
        run: |
          Invoke-WebRequest https://playit.gg/downloads/playit-windows-amd64.exe -OutFile playit.exe

      - name: Start Playit tunnel
        shell: pwsh
        run: |
          .\playit.exe

      - name: Keep VM alive
        shell: pwsh
        run: |
          Write-Host "Windows VM running..."
          $end = (Get-Date).AddMinutes(120)
          while((Get-Date) -lt $end){
              Start-Sleep -Seconds 60
          }
